"""Constants for HA Daily Counter integration."""

DOMAIN = "ha_daily_counter"

# Config Options
CONF_NAME = "name"
CONF_RESET_CYCLE = "reset_cycle"

RESET_CYCLE_QUARTER_HOURLY = "quarter-hourly"
RESET_CYCLE_HOURLY = "hourly"
RESET_CYCLE_DAILY = "daily"
RESET_CYCLE_WEEKLY = "weekly"
RESET_CYCLE_MONTHLY = "monthly"
RESET_CYCLE_BIMONTHLY = "bimonthly"
RESET_CYCLE_QUARTERLY = "quarterly"
RESET_CYCLE_YEARLY = "yearly"
RESET_CYCLE_NONE = "none"

RESET_CYCLES = [
    RESET_CYCLE_QUARTER_HOURLY,
    RESET_CYCLE_HOURLY,
    RESET_CYCLE_DAILY,
    RESET_CYCLE_WEEKLY,
    RESET_CYCLE_MONTHLY,
    RESET_CYCLE_BIMONTHLY,
    RESET_CYCLE_QUARTERLY,
    RESET_CYCLE_YEARLY,
    RESET_CYCLE_NONE,
]

# Attributes
ATTR_TRIGGER_ENTITY = "trigger_entity"
ATTR_TRIGGER_STATE = "trigger_state"

# Defaults
DEFAULT_NAME = "Daily Counter"
DEFAULT_RESET_CYCLE = RESET_CYCLE_DAILY
